import React from 'react';
import { useApp } from '../../context/AppContext';

export const HomeNewsBanner: React.FC = () => {
  const { navigate } = useApp();

  return (
    <header className="section_news padding-bottom-md"><div className="container no-pd-mobile"><div className="w-layout-grid news_component is-updated"><div id="w-node-_1e4204f1-8735-2699-90ee-ac9a5dba0102-84876d75" className="news_content"><h2 className="heading-style-h2 is-text-white">Join our global community</h2><p>Connect with traders around the world to exchange insights, explore portfolios, and gain valuable expertise.</p><div className="news_button-group is-mobile-wide"><div data-dwp-user-type="authenticated" data-wf--design-system-enterprise-copy--authenticated-block--variant="base" className="design-system-enterprise-copy--auth_component"><div className="design-system-enterprise-copy--auth_button_wrapper"><a data-wf--design-system-enterprise-copy--button--variant="coral-solid" href="https://home.deriv.com/dashboard" className="design-system-enterprise-copy--button w-inline-block"><div data-traking="button-text" className="design-system-enterprise-copy--button_text">Trade now</div></a></div></div><div data-dwp-user-type="unauthenticated" data-wf--design-system-enterprise-copy--unauthenticated-block--variant="base" className="design-system-enterprise-copy--auth_component"><div className="design-system-enterprise-copy--auth_wrapper"><div className="design-system-enterprise-copy--auth_button_wrapper"><a data-wf--design-system-enterprise-copy--button--variant="coral-solid" href="https://home.deriv.com/dashboard/signup" className="design-system-enterprise-copy--button w-inline-block"><div data-traking="button-text" className="design-system-enterprise-copy--button_text">Open account</div></a></div></div></div></div></div><div className="news_image_wrapper is-reversed"><div className="news_image_overlay is-reversed"></div><div className="community_lottie" data-w-id="a92bd73a-7d16-dbff-fe2e-871ea9f17796" data-animation-type="lottie" data-src="https://cdn.prod.website-files.com/67c187cdf63c319864a8482d/687de219fe7dc7dc0c347d00_Community.lottie" data-loop="1" data-direction="1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-default-duration="0" data-duration="5.016666666666667" data-loading="eager"></div></div></div></div></header>
  );
};
