import { Course } from '../types';

export const COURSES_DATA: Course[] = [
  {
    id: 'course-1',
    slug: 'mastering-deriv-synthetic-indices',
    title: 'Mastering Deriv Synthetic Indices',
    subtitle: 'From basic continuous random-walk mechanics to advanced multi-timeframe breakout strategies on Volatility and Crash/Boom indices.',
    description: 'A comprehensive, step-by-step masterclass designed for traders who want to gain an edge in Deriv’s proprietary synthetic markets. Learn the exact mathematics behind constant variance, avoid common lot-size traps, and master 24/7 technical execution.',
    category: 'synthetic-indices',
    categoryLabel: 'Synthetic Indices',
    difficulty: 'intermediate',
    duration: '2h 45m',
    totalLessons: 9,
    rating: 4.9,
    reviewCount: 3840,
    studentsCount: 28400,
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    author: {
      name: 'Julian Vance',
      role: 'Head of Quantitative Strategies at Deriv',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&h=200&q=80',
      bio: 'Julian has architected quantitative risk parameters for institutional liquidity providers and retail synthetic engines.'
    },
    learningOutcomes: [
      'Understand how cryptographically seeded RNGs create continuous, non-manipulated pricing.',
      'Differentiate between Volatility 10, 25, 75, and 100 volatility ranges.',
      'Trade Crash and Boom tick spikes using high-probability supply and demand zones.',
      'Configure Deriv MT5 custom indicators and automatic trailing stop orders for synthetic assets.',
      'Formulate a risk-per-trade matrix that prevents account over-leveraging.'
    ],
    prerequisites: [
      'Basic familiarity with candlestick charts',
      'A free Deriv demo account to practice setups risk-free'
    ],
    modules: [
      {
        id: 'mod-1',
        title: 'Module 1: Foundations of Synthetic Markets',
        lessons: [
          {
            id: 'les-1-1',
            title: '1.1 What are Synthetics & How Do They Differ from Forex?',
            duration: '14 min',
            videoDurationSeconds: 840,
            description: 'Deconstruct the core architecture of synthetic indices, compare them with traditional forex markets, and understand why they are completely unaffected by real-world geopolitical news.',
            videoSummary: 'In this introductory lesson, Julian Vance demonstrates how Deriv Synthetic Indices maintain algorithmic constancy. We inspect the underlying tick generation engine, discuss how transparency is audited by independent third parties, and highlight why there are no slippages or unexpected weekend gaps.',
            keyTakeaways: [
              'Synthetics operate 24 hours a day, 7 days a week, 365 days a year.',
              'No news shocks or sudden central bank rate decision disruptions.',
              'Audited cryptographic RNG engines provide fair, tamper-proof execution.'
            ],
            quiz: {
              question: 'Why do Deriv Synthetic Indices NOT experience weekend gaps or sudden news slippages?',
              options: [
                'Because the market is closed on weekends like Forex',
                'Because prices are generated by audited mathematical random number algorithms independent of real-world news events',
                'Because government regulators freeze price spikes',
                'Because trading volume is always equal between buyers and sellers'
              ],
              correctIndex: 1,
              explanation: 'Deriv synthetic indices are based on transparent, audited cryptographic random number generators that simulate market volatility without being tied to external economic news or market hours.'
            }
          },
          {
            id: 'les-1-2',
            title: '1.2 Navigating the Volatility Index Spectrum (10 to 100)',
            duration: '18 min',
            videoDurationSeconds: 1080,
            description: 'Analyze the mathematical variance differences between Volatility 10, 25, 50, 75, and 100, including (1s) tick frequencies.',
            videoSummary: 'This video covers the volatility spectrum. We examine side-by-side charts showing Volatility 10 (gentle, steady trends) versus Volatility 75 and 100 (rapid, high-frequency expansions). You will learn how to pick the right index matching your psychological tolerance and trading timeframe.',
            keyTakeaways: [
              'The number (e.g. 75) indicates constant annualized volatility.',
              '(1s) indices produce one tick per second, creating consistent candle structure.',
              'Never apply identical stop loss distance in points across different volatility indices.'
            ],
            quiz: {
              question: 'What does the number in "Volatility 75 Index" represent?',
              options: [
                'A 75% chance that the market will rise',
                'A fixed, constant annualized volatility level of 75%',
                'The minimum lot size required to trade the instrument',
                'The number of pips required for break-even'
              ],
              correctIndex: 1,
              explanation: 'The number denotes the fixed annualized standard deviation maintained by the synthetic pricing engine.'
            }
          },
          {
            id: 'les-1-3',
            title: '1.3 Lot Sizing, Margin & Pip Values on Deriv MT5',
            duration: '22 min',
            videoDurationSeconds: 1320,
            description: 'Master point value calculations and margin formulas so you never inadvertently over-leverage a synthetic position.',
            videoSummary: 'We walk through real trade examples inside the Deriv MT5 terminal. Watch how point values and margin requirements differ between standard currency pairs and synthetic indices, and learn to use the Deriv Trader margin calculator.',
            keyTakeaways: [
              'Always calculate pip value before opening trades on high-number indices.',
              'Use micro lots (0.001 to 0.01) when first adapting to Volatility 75 or 100.',
              'Check your free margin percentage before stacking multiple entries.'
            ]
          }
        ]
      },
      {
        id: 'mod-2',
        title: 'Module 2: Trading Crash & Boom Indices',
        lessons: [
          {
            id: 'les-2-1',
            title: '2.1 Understanding Crash and Boom Probability Distributions',
            duration: '19 min',
            videoDurationSeconds: 1140,
            description: 'Delve into the Poisson distribution governing sudden price crashes and boom rallies on 500 and 1000 tick indices.',
            videoSummary: 'Julian explains the mathematics of Crash 500/1000 and Boom 500/1000. Learn why the gambler’s fallacy ruins uneducated traders and how to read higher-timeframe market structure to anticipate high-probability zones.',
            keyTakeaways: [
              'Spikes happen in a single tick and cannot be paused mid-candle.',
              'Each tick has independent probability; spikes are not "due" because time has elapsed.',
              'Trading *with* the spike yields asymmetric risk-to-reward benefits.'
            ],
            quiz: {
              question: 'What is the primary danger of scalping small tick gains against the spike on Crash or Boom?',
              options: [
                'There are high swap fees charged every 5 minutes',
                'A single sudden counter-spike can erase dozens of small accumulated tick gains',
                'Deriv does not allow positions shorter than 10 minutes',
                'Spreads widen continuously during normal ticks'
              ],
              correctIndex: 1,
              explanation: 'Because a spike drops or rises dozens of points in a single tick, scalping against the spike exposes the trader to massive asymmetric downside if a spike occurs.'
            }
          },
          {
            id: 'les-2-2',
            title: '2.2 Catching Spikes at Higher-Timeframe Supply & Demand',
            duration: '25 min',
            videoDurationSeconds: 1500,
            description: 'Learn how to identify institutional-grade order blocks and resistance zones on 15-minute and 1-hour charts to catch downward Crash spikes.',
            videoSummary: 'A step-by-step trading blueprint for entering high-probability sell limits on Crash indices and buy limits on Boom indices with controlled, tight stop losses.',
            keyTakeaways: [
              'Mark key turning points on the 1-hour chart before zooming in.',
              'Limit your risk window to 10–15 ticks maximum past the rejection level.',
              'When the spike hits, scale out 50% and move your stop to breakeven.'
            ]
          }
        ]
      },
      {
        id: 'mod-3',
        title: 'Module 3: Advanced Execution & Strategy Blueprint',
        lessons: [
          {
            id: 'les-3-1',
            title: '3.1 The 20 EMA Dynamic Trend Continuation Strategy',
            duration: '21 min',
            videoDurationSeconds: 1260,
            description: 'Implement a trend-following system using dynamic moving averages on Volatility 75 (1s).',
            videoSummary: 'We examine the 20 EMA pullback system. Learn how to filter out fake breakouts, wait for confirmation candles, and execute trades with mechanical precision.',
            keyTakeaways: [
              'Trade only in the direction of the 200 EMA trend slope.',
              'Enter when price tests the 20 EMA with a pin bar or engulfing confirmation.',
              'Target a minimum of 1:2.5 risk-reward ratio.'
            ]
          },
          {
            id: 'les-3-2',
            title: '3.2 Multipliers Strategy: Capped Risk with Maximum Upside',
            duration: '16 min',
            videoDurationSeconds: 960,
            description: 'Combine technical breakout patterns with Deriv Multiplier contracts and Deal Cancellation.',
            videoSummary: 'Discover how Multipliers allow you to trade aggressive momentum without fearing unexpected debt or liquidation calls.',
            keyTakeaways: [
              'Use Deal Cancellation during volatile breakout attempts.',
              'Set automated Take Profit targets to secure parabolic expansions.',
              'Downside loss is strictly capped to your original stake amount.'
            ]
          }
        ]
      }
    ]
  },
  {
    id: 'course-2',
    slug: 'introduction-to-forex-trading',
    title: 'Introduction to Forex Trading',
    subtitle: 'Build a solid foundation in currency pairs, market dynamics, pip values, leverage, and economic indicators.',
    description: 'Everything a beginner needs to start trading the world’s largest financial market. Understand base and quote currencies, bid-ask spreads, order execution types, and the role of global central banks.',
    category: 'forex',
    categoryLabel: 'Forex',
    difficulty: 'beginner',
    duration: '1h 50m',
    totalLessons: 6,
    rating: 4.8,
    reviewCount: 5210,
    studentsCount: 41200,
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    author: {
      name: 'Elena Rostova',
      role: 'Chief Currency Analyst',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&h=200&q=80',
      bio: 'Elena provides daily macroeconomic commentary and currency risk modeling for global traders.'
    },
    learningOutcomes: [
      'Read currency quotes and calculate pips, lots, and profit/loss accurately.',
      'Understand how the US Dollar, Euro, British Pound, and Japanese Yen interact.',
      'Identify how interest rate decisions and inflation numbers trigger market volatility.',
      'Place market, limit, stop-loss, and take-profit orders on Deriv platforms.'
    ],
    prerequisites: ['No prior trading experience required.'],
    modules: [
      {
        id: 'fx-mod-1',
        title: 'Module 1: Currency Market Basics',
        lessons: [
          {
            id: 'fx-les-1',
            title: '1.1 How Currency Pairs Work: Base vs Quote',
            duration: '15 min',
            videoDurationSeconds: 900,
            description: 'Learn the structure of major, minor, and exotic currency pairs and how exchange rates are quoted.',
            videoSummary: 'Elena breaks down quotes like EUR/USD = 1.0850, explaining what buying and selling actually means when trading two currencies simultaneously.',
            keyTakeaways: [
              'The first currency is the base; the second is the quote currency.',
              'Exchange rate shows how much quote currency buys one unit of base currency.'
            ],
            quiz: {
              question: 'In the currency pair EUR/USD, which is the base currency?',
              options: ['USD', 'EUR', 'Both equally', 'Neither, it depends on whether you buy or sell'],
              correctIndex: 1,
              explanation: 'In any currency quote, the first currency listed is always the Base currency, and the second is the Quote (or Term) currency.'
            }
          },
          {
            id: 'fx-les-2',
            title: '1.2 What is a Pip and How to Calculate Its Value?',
            duration: '18 min',
            videoDurationSeconds: 1080,
            description: 'Master the universal unit of measurement in forex: percentage in point (pip) and pipettes.',
            videoSummary: 'Step-by-step walkthrough calculating pip values for 4-decimal pairs and Japanese Yen pairs across standard, mini, and micro lots.',
            keyTakeaways: [
              'For most pairs, a pip is the 4th decimal place (0.0001).',
              'For JPY pairs, a pip is the 2nd decimal place (0.01).'
            ]
          }
        ]
      },
      {
        id: 'fx-mod-2',
        title: 'Module 2: Market Drivers & Order Types',
        lessons: [
          {
            id: 'fx-les-3',
            title: '2.1 Economic Calendar: Trading Central Bank News',
            duration: '24 min',
            videoDurationSeconds: 1440,
            description: 'How to read interest rate statements, CPI inflation reports, and NFP data releases without getting whipsawed.',
            videoSummary: 'Elena shows how to use economic calendars to anticipate high-volatility events and protect your open positions.',
            keyTakeaways: [
              'High-impact news events cause temporary spread widening.',
              'Interest rate differentials are the primary driver of multi-month currency trends.'
            ]
          }
        ]
      }
    ]
  },
  {
    id: 'course-3',
    slug: 'deriv-mt5-complete-guide',
    title: 'Deriv MT5: Complete Beginner to Pro',
    subtitle: 'Set up your charts, manage pending orders, install expert advisors, and execute like a professional trader on MetaTrader 5.',
    description: 'Master the world’s leading multi-asset trading terminal on Deriv. Learn chart templates, one-click execution, trade terminal shortcuts, depth of market, and mobile MT5 synchronization.',
    category: 'synthetic-indices',
    categoryLabel: 'Platforms & Tools',
    difficulty: 'beginner',
    duration: '2h 10m',
    totalLessons: 7,
    rating: 4.9,
    reviewCount: 4120,
    studentsCount: 35600,
    imageUrl: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    author: {
      name: 'Marcus Sterling',
      role: 'Senior Technical Analyst',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=200&q=80',
      bio: 'Marcus has customized algorithmic order terminals for over 16 years.'
    },
    learningOutcomes: [
      'Download, log in, and configure Deriv MT5 server credentials.',
      'Customize clean chart workspaces, color schemes, and multi-monitor layouts.',
      'Execute market execution, buy stops, sell limits, and trailing stops with precision.',
      'Manage margin levels, free margin, and leverage settings.'
    ],
    prerequisites: ['A Deriv MT5 demo or real account.'],
    modules: [
      {
        id: 'mt5-mod-1',
        title: 'Module 1: Platform Setup & Chart Configuration',
        lessons: [
          {
            id: 'mt5-les-1',
            title: '1.1 Connecting to Deriv MT5 Demo & Real Servers',
            duration: '12 min',
            videoDurationSeconds: 720,
            description: 'Everything you need to know to locate your server credentials in Deriv Dashboard and log in seamlessly.',
            videoSummary: 'Marcus guides you step-by-step through logging in to your Deriv MT5 desktop, web, or mobile app without server connection errors.',
            keyTakeaways: [
              'Verify whether your account is hosted on Deriv-Server or Deriv-Demo.',
              'Keep your master password secure and separate from your investor view password.'
            ]
          },
          {
            id: 'mt5-les-2',
            title: '1.2 Setting Up Professional Chart Templates & Profiles',
            duration: '16 min',
            videoDurationSeconds: 960,
            description: 'Create clean, readable charts with custom colors, candlesticks, grid toggles, and saved indicator profiles.',
            videoSummary: 'How to save custom templates in MT5 so every new currency pair or synthetic index opens with your preferred indicators automatically.',
            keyTakeaways: [
              'Save your favorite layout as "default.tpl" to apply it to all new charts.',
              'Use keyboard shortcuts (F8 for properties, F9 for new order) for lightning-fast workflow.'
            ]
          }
        ]
      }
    ]
  }
];
